In [5]:
import numpy as np
p = 0.05*np.ones((4,5))
colors = np.array([['R','G','G','R','R'],
          ['R','R','G','R','R'],
          ['R','R','G','G','R'],
          ['R','R','R','R','R']])
measurements = np.array(['G','G','G','G','G'])
motions = np.array([[0,0],[0,1],[1,0],[1,0],[0,1]])
sensor_right = 0.7
p_move = 0.8
def sense(p,Z):
    q = []
    q1 = []
    for i in range(p.shape[0]):
        for j in range(p.shape[1]):
            pHit = (Z==colors[i][j])
            q1.append(pHit*p[i][j]*sensor_right+(1-pHit)*p[i][j]*(1-sensor_right))
        q.append(q1)
        q1 = []
    sum_q = np.sum(q)
    for i in range(p.shape[0]):
        for j in range(p.shape[1]):
            q[i][j] = q[i][j]/sum_q
    return np.array(q)
def move(p,U):
    q = []
    q1 = []
    for i in range(len(p)):
        for j in range(p.shape[1]):
            s = p_move*(p[(i-U[0])%len(p)][(j-U[1])%(p.shape[1])]) +  (1-p_move)*p[i][j]
            q1.append(s)
        q.append(q1)
        q1 = []
    return np.array(q)
def localize(q,colors,measurements,motions,sensor_right,p_move):
    for i in range(len(measurements)):
        q = move(q,motions[i])
        q = sense(q,measurements[i])
    return q
p = localize(p,colors,measurements,motions,sensor_right,p_move)
print(p)

[[0.01105981 0.02464042 0.06799663 0.04472487 0.02465153]
 [0.0071532  0.01017133 0.08696596 0.0798843  0.00935067]
 [0.00739737 0.00894373 0.11272965 0.35350723 0.04065549]
 [0.00910651 0.0071532  0.01434922 0.04313329 0.0364256 ]]
